version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: gijsbersvanwijk/get-started:demo-docker-app
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "5000:8080"
